[Interface]
PrivateKey = uPfMNxpKXDYNCSd9rXykRO13yVjfQs+MnKIQly1xDG8=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 1.1.1.1,1.0.0.1

# Uncomment the next line to set a custom MTU
# This might impact performance, so use it only if you know what you are doing
# See https://github.com/nitred/nr-wg-mtu-finder to find your optimal MTU
# MTU = 1420

[Peer]
PublicKey = wvuhQ53Viim1W8Z65VC22DQ/QOFPuNIANCR68Ls2Dko=
PresharedKey = 6hkey96J3g/s4FwpXYfWr5O2Sbo6SrkU6Aiud9dcmkI=
Endpoint = 43.129.50.254:59689
AllowedIPs = 0.0.0.0/0,::/0